### PR TITLE
Add tags to ignore all-contributors table on docs.imgix.com

### PR DESCRIPTION
**Pull request by jayeb**
## Description

This PR adds a pair of `<!-- ix-docs-ignore -->` comments around the table in the "Contributors" section of the README.md doc. We've decided that trying to render All-Contributor's table layout nicely is too much effort (since we have no control over the markup) when rendering our SDK READMEs directly on docs.imgix.com. The tags added in this PR will instruct the build pipeline over on the Docs side to ignore the annotated section.

## Checklist: Fixing typos/Doc change

- [x] The target branch is `beta`. This is important for our CI/CD config.
- [x] Each commit follows the conventional commit spec format: e.g. `chore(readme): fixed typo`. See the end of this file for more information.

### CODE REVIEW

**Comment by frederickfogerty** [comment]
I think commitlint doesn't like the PR title but that doesn't matter since I'll rebase and merge here. For future reference, your original `docs:` was the best commit message here, apologies if commitlint made you change it.

**Comment by jayeb** [comment]
TBH I don't know what commit-lint's beef is with me, but I changed from `docs:` to `chore:` because of this line in the PR template:

> `type` can be one of `feat`, `fix`, `test`, or `chore`.

Perhaps that should be updated?

**Comment by frederickfogerty** [comment]
Yeah true, I'll update that now.

**Comment by sherwinski** [comment]
FWIW commit-lint always yells at me when I add a scope to the commit, even though it's [supposedly optional](https://www.conventionalcommits.org/en/v1.0.0/#summary).

**Comment by frederickfogerty** [comment]
🙃

**Pull request merged**
